<?php
class Config {
    public static $rainColor = 'blue';

    public static $mineralColor = 'brown';
    public static $strongMineralColor = 'yellow';

    public static $playerHeadColor = 'bold_gray';
    public static $playerTailColor = 'bold_gray';

    public static $toxicWasteColor = 'bold_green';

    public static $crystalColor = 'purple';

    public static $meteorHeadColor = 'dark_gray';
    public static $meteorTailColor = 'red';

    public static $plantColor = 'green';
    public static $enlightenedPlantColor = 'green';
}